/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package light;

public class Library {
    public static void main(String[] args) {
        Spectrum ray = Spectrum.pure(Color.FIRE, 2)
            .add(Spectrum.pure(Color.PUSH, 2)
            .add(Spectrum.pure(Color.FIRE, 4)));

        System.out.println(
            ray.split(Color.FIRE)
        );
    }
}
